apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-fuhz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-fuhz
    app.kubernetes.io/part-of: my-app
  name: devfile-sample-fuhz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-fuhz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-fuhz
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rorai-tenant/my-app/devfile-sample-fuhz@sha256:e0e69fce6502d7824ec3b356c8558acf4e21679dbb3fe0ece71e411d84ec9fa9
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
